on:
  push:
    branches:
      - main
name: Push Main
jobs:
  reusable:
    uses: xyngular/reusable-github-workflows/.github/workflows/py-push-main.yml@main
    with:
      real-publish: true
    secrets: inherit
